name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet build src/NetUlid.sln
    - name: Run tests
      run: dotnet test --no-build src/NetUlid.sln
